
import type { Metadata } from 'next'
import { Inter } from 'next/font/google' 
import '../globals.css';
import { ToastContainer } from "react-toastify"


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Pagamento Online', 
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode 
}) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>

        {children}
        <ToastContainer />
        </body>
    </html>
  )
}
