import Image from 'next/image'
import Head from 'next/head';
import TopCards from "@/components/TopCards";

export default function Home() {
  return (
    <>
    <Head>
    <title>Create next app</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
  
  <h1>hello world</h1>
  <TopCards/>
  </>
 )
    
   
  
}
