
'use-client';
import Head from 'next/head';
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
// import BarChart from "@/components/BarChart";
import TopCards from "@/components/TopCards";
import { Bar } from 'react-chartjs-2';




export default function Dashboard (){
    
    return  (
        <div className="">
        <Head>
      <title>Create next app</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
      </Head>
      
      
           
            <TopCards/>
            
            </div>
            
        

    )  
    
}
